import Head from "next/head";

export default function Bookmarks() {
	return (
		<>
			<Head>
				<title>Bookmarks / Twitter</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<div>Bookmarks</div>
		</>
	);
}
