import Head from "next/head";

export default function Explore() {
	return (
		<>
			<Head>
				<title>Explore / Twitter</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<div>Explore</div>
		</>
	);
}
