import Head from "next/head";

export default function Lists() {
	return (
		<>
			<Head>
				<title>Lists / Twitter</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<div>Lists</div>
		</>
	);
}
