import Head from "next/head";

export default function Messages() {
	return (
		<>
			<Head>
				<title>Messages / Twitter</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<div>Messages</div>
		</>
	);
}
