import Head from "next/head";
import styled from "styled-components";

export default function Notifications() {
	return (
		<>
			<Head>
				<title>Notifications / Twitter</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<Main>Notifications</Main>
		</>
	);
}

const Main = styled.main`
	display: flex;
	width: 100%;
	gap: 0 30px;
	min-height: 100vh;
`;
